name: build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'python-ubuntu-runtime.Dockerfile'

jobs:
  build-python-ubuntu-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make python-runtime

      